# Generated by Django 5.0.7 on 2025-09-26 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reglas', models.JSONField(blank=True, default=dict)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('opciones', models.JSONField(blank=True, default=list)),
                ('quorum', models.IntegerField(default=0)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('ce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votaciones', to='governance.communityenergy')),
            ],
        ),
    ]
