# Generated by Django 5.0.7 on 2025-09-26 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultingContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.JSONField(blank=True, default=dict)),
                ('contrato_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulting', to='core.contract')),
                ('paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulting.consultingpackage')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=128)),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=12)),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='core.actor')),
            ],
        ),
        migrations.AddField(
            model_name='consultingpackage',
            name='servicios',
            field=models.ManyToManyField(related_name='paquetes', to='consulting.consultingservice'),
        ),
    ]
