# Generated by Django 5.0.7 on 2025-09-26 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_carga', models.JSONField(blank=True, default=dict)),
                ('precio_obj', models.DecimalField(decimal_places=4, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='core.actor')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_ref', models.DecimalField(decimal_places=4, max_digits=12)),
                ('capacidad_kw', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.actor')),
            ],
        ),
    ]
