# Generated by Django 5.0.7 on 2025-09-26 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=16)),
                ('kwh', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tarifa', models.DecimalField(decimal_places=4, max_digits=12)),
                ('bruto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('neto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='core.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='core.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=128)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ref', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='finance.wallet')),
            ],
        ),
    ]
