# Generated by Django 5.0.7 on 2025-09-26 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='OPEN', max_length=32)),
                ('hitos', models.JSONField(blank=True, default=list)),
                ('instalador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='core.actor')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='core.project')),
            ],
        ),
    ]
