# Generated by Django 5.0.7 on 2025-09-27 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_age_userprofile_avatar_file_and_more'),
        ('epc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoofListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=255)),
                ('sombras', models.CharField(blank=True, default='', max_length=255)),
                ('fotos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='core.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capex', models.DecimalField(decimal_places=2, max_digits=14)),
                ('hitos', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='PENDING', max_length=32)),
                ('instalador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.actor')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='epc.rooflisting')),
            ],
        ),
    ]
