# Generated by Django 5.0.7 on 2025-09-26 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INVESTOR', 'Investor'), ('ROOF_OWNER', 'Roof Owner'), ('BUYER', 'Buyer'), ('COMMUNITY', 'Community'), ('INSTALLER', 'Installer'), ('IMPORTER', 'Importer'), ('VENDOR', 'Vendor'), ('CONSULTANT', 'Consultant')], max_length=32)),
                ('kyb_kyc', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PPA', 'Ppa'), ('LEASING', 'Leasing'), ('COMMUNITY', 'Community'), ('SERVICIO', 'Servicio')], max_length=16)),
                ('tarifa', models.DecimalField(decimal_places=4, max_digits=12)),
                ('vigencia', models.CharField(max_length=64)),
                ('terms', models.JSONField(blank=True, default=dict)),
                ('partes', models.ManyToManyField(related_name='contracts', to='core.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RESID', 'Resid'), ('IND', 'Ind'), ('CE', 'Ce')], max_length=16)),
                ('potencia_kw', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ubicacion', models.CharField(max_length=255)),
                ('estado', models.CharField(default='INIT', max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=16)),
                ('kwh_gen', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('kwh_cons', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('kwh_exced', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='core.project')),
            ],
        ),
    ]
