# Generated by Django 5.0.7 on 2025-09-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contract_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
